### ISSUE TITLE
'No Response'

### ISSUE THREAD

**Issue by christensonautohome** [andylittle/envisakit#2]
Great work on this!  Really love the functions this adds to my home automation. 

However I tend to get a 'No Response' value when i check the status in the HomeKit app on iOS.  If i hold the Alarm accessory it will pull up and load the Home/Away/Night/Off then when i go back it updates the value.
any ideas?  Is this just a time out issue between HomeKit asking for a status and the delay of the Envisalink module responding?

**Comment by andylittle** [comment]
I did not develop this.  I found it on GitHub and was using it along with cron to control my alarm.  The original repository was removed from so I put this one back up.  I have since moved to Home Assistant and no longer use this.
I have the EnvisaLink EVL-4 and it does not always respond to commands and briefly falls off the network.  It missed the disarm command today and my wife set off the alarm feeding the cats.

**Comment by christensonautohome** [comment]
i'll try updating the cash timeout and see if that fixes the problem.
thanks for adding it back... I did also see the old repository was removed.  Figured you picked it up.... anyway thinks for adding it back.

**Comment by christensonautohome** [comment]
Just wanted to document my findings...
1) i changed 'cash timeout' to 25 seconds and updated the 'periodic update' to true.  this has solved all timeout issues
2) i noticed my alarm was switching to "STAY" mode automatically and upon reading i saw this in the VISTA manual:

**Auto-Stay Arm**
0 = no
1 = partition 1 only
2 = partition 2 only
3 = both partitions
With this field enabled and system armed in AWAY mode at a
keypad (non-RF device), the system automatically reverts to
armed STAY (or INSTANT) mode if a door is not opened and
shut within the programmed exit delay time. An Opening report
followed by an Armed Stay report is sent to the Central Station.
Any RF device that arms the system AWAY overrides this
feature and the system remains armed in the AWAY mode

Seems like if you want the alarm to stay in AWAY mode (for me it's important for arming my motion sensors) you MUST make the changes above to your alarm panel.  
A manual for the 15p and 20p can be found here:
http://www.nationwidesecuritycorp.com/wp-content/uploads/FA160C-Install-Manual.pdf

**Comment by christensonautohome** [comment]
Last update... sorry. should have included this on the previous message
To enter programing mode on the alarm... 
1) disconnect battery back up 
2) remove power from the vista panel  
3) plug back in and within 50 seconds press * and # on your key pad 
4) press *84 to enter the auto-alarm settings and hit 0 (zero); you should hear a beep confirmation
5) exit program mode by typing *98 or *99 (if you want to keep installer code option do *99 but honestly if you are doing this you should probably remove installer code cause you can do everything using the enter the programing area using the method i detailed above).
